import { Inter, Roboto_Flex} from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto_Flex({
  subsets: ["latin"],
  display:"swap"
})
export const metadata = {
  title: "Transaction Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" class="dark">
      <body className={cn(roboto.className, "min-h-screen bg-gradient-to-t from-blue-900 to-indigo-900 flex justify-center")}>{children}</body>
    </html>
  );
}
